### ISSUE TITLE
Export training functionality

### ISSUE THREAD

**Issue by tamuhey** [PKSHATechnology-Research/camphr#11]
1. Hydra supports convert the CLI to pip package.
2. Users can use the config by the name: https://github.com/facebookresearch/hydra/tree/master/plugins/examples/example_configsource_plugin
3. Users can write their own training scripts as follows:

```python
@hydra.main(config_path='user_config.yaml')
def main(cfg):
  ...
```

user_config.yaml:
```yaml
defaults:
  - campr/base
  - user_overrides
```

camphr/base.yaml: (this is packages with camphr).
```yaml
model:
    lang:
        name: ???
    optimizer:
        class: transformers.optimization.AdamW
        params:
            eps: 1.0e-05
            lr: 1.0e-03
train:
    data:
        ndata: -1
        path: ???
        val_size: 0.1
    nbatch: 128
    niter: 30
```

user_overrides.yaml (the user is providing this next to his config file):
```yaml
model:
    lang:
        name: ja

train:
    data:
        ndata: -1
        path: ~/train.jsonl
```
